### ISSUE TITLE
絵文字について（UTF-8 サポート）

### ISSUE THREAD

**Issue by m2ym** [wachikun/yaskkserv#2]
yaskkserv で Unicode 絵文字を入力できるとすごく嬉しいのですが、 Unicode エンコーディング（例えば UTF-8 ）をサポートするのはかなり大変なのでしょうか。公式ページに「面倒」と書かれているのを見つけ、どのあたりが面倒なのか気になりました。教えていただければ幸いです。

**Comment by wachikun** [comment]
辞書や探索コードの構造/実装が EUC 前提になっているためです。
具体的には、見出し文字列などが EUC (上位バイトが同一)であることを期待したコードになっていたりします。

最初の設計時に汎用的にするか、 EUC 前提にするかは悩んだのですが、組み込みなどで単純な実装を目指していたことも大きく、後者を採りました。

最近の SKK-ML などを見ていて、やはり UTF-8 対応は必要だと認識しており、辞書とコードに UTF-8 用のちょっとした対応を入れることでなんとかなりそうならば、 yaskkserv_hairy あたりで対応できたらいいなと思っています。

**Comment by m2ym** [comment]
なるほど、了解しました。自分では何とも出来そうにないので気長に待つことにします。便利なソフトウェアをどうもありがとうございます。

**Comment by wachikun** [comment]
yaskkserv とは別となりますが [yaskkserv2](https://github.com/wachikun/yaskkserv2) で utf-8 辞書に対応しました。
但し、 SKK protocol 的に EUC を要求するため、別途 ddskk 側のコードを utf-8 対応させる必要はあります。
